version: '3.7'
services:
  ui-hyperledger:
    build:
      context: ./client/
    command: npm start
    networks:
      - tools_proxy
    ports:
      - "8081:3000"
    environment:
      REACT_APP_REST_API_URL: http://localhost:8091
networks:
  tools_proxy:
    external:
      name: tools_network
